#!/usr/bin/env python3
# author: John Sullivan, github.com/antithalian

import requests
import json

def word_handler(message):
    '''Gives a random fake word and definition (generated by a GPT-2 neural network)'''

    # url for thisworddoesnotexist's random API endpoint
    url = 'https://www.thisworddoesnotexist.com/api/random_word.json'

    respond = requests.get(url)

    if respond.status_code == 200:
        respond = json.loads(respond.text) # load the JSON response

        # get the parts of the output string
        word = respond['word']['word']
        typ = ' (' + respond['word']['pos'] + ')'
        defn = ' - ' + respond['word']['definition']

        # put the bits together and return
        return (word.capitalize() + typ + defn)
        
    # if the response is an error, tell the caller what it was
    else:
        return 'Error {}: could not retrieve word'.format(respond.status_code)